source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NemoContactPicker_Example', :exclusive => true do
  pod "NemoContactPicker", :path => "../"
end

target 'NemoContactPicker_Tests', :exclusive => true do
  pod "NemoContactPicker", :path => "../"

  
end
